using System;
using FaturamentoService.Data;
using FaturamentoService.Services;
using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

// Configuração de Controllers
builder.Services.AddControllers();

// Configuração de CORS para o Frontend Angular
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

// Configuração do PostgreSQL com Entity Framework Core
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? "Host=localhost;Port=5432;Database=korp_db;Username=postgres;Password=1234;Include Error Detail=true";

builder.Services.AddDbContext<FaturamentoDbContext>(options =>
{
    options.UseNpgsql(connectionString);
});

// Configuração do HttpClient para comunicação com o EstoqueService
var estoqueServiceUrl = builder.Configuration["Services:EstoqueServiceUrl"] ?? "http://localhost:5001/";
builder.Services.AddHttpClient<IEstoqueServiceClient, EstoqueServiceClient>(client =>
{
    client.BaseAddress = new Uri(estoqueServiceUrl);
    client.Timeout = TimeSpan.FromSeconds(10);
});

// Injeção de Dependência dos Serviços de Domínio
builder.Services.AddScoped<INotaFiscalService, NotaFiscalService>();

// Configuração do Swagger / OpenAPI
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Korp - Faturamento Service API",
        Version = "v1",
        Description = "Microsserviço de Emissão e Gestão de Notas Fiscais - Teste Técnico Korp"
    });
});

var app = builder.Build();

// Inicialização Automática da Estrutura do Banco de Dados no PostgreSQL
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    var logger = services.GetRequiredService<ILogger<Program>>();
    try
    {
        var context = services.GetRequiredService<FaturamentoDbContext>();
        logger.LogInformation("Garantindo estrutura de tabelas do Faturamento no PostgreSQL (Schema: faturamento)...");

        context.Database.ExecuteSqlRaw(@"
            DO $$
            BEGIN
                IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'faturamento') THEN
                    CREATE SCHEMA faturamento;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS faturamento.notas_fiscais (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                numero integer NOT NULL,
                status integer NOT NULL,
                data_criacao timestamp with time zone NOT NULL DEFAULT (NOW()),
                data_fechamento timestamp with time zone,
                observacao character varying(500)
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_notas_fiscais_numero"" ON faturamento.notas_fiscais (numero);

            CREATE TABLE IF NOT EXISTS faturamento.itens_nota_fiscal (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nota_fiscal_id integer NOT NULL REFERENCES faturamento.notas_fiscais(id) ON DELETE CASCADE,
                produto_id integer NOT NULL,
                codigo_produto character varying(50) NOT NULL,
                descricao_produto character varying(200) NOT NULL,
                quantidade integer NOT NULL
            );

            CREATE INDEX IF NOT EXISTS ""IX_itens_nota_fiscal_nota_fiscal_id"" ON faturamento.itens_nota_fiscal (nota_fiscal_id);
        ");

        logger.LogInformation("Estrutura do banco do Faturamento inicializada com sucesso.");
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Erro ao inicializar o banco de dados do Faturamento.");
    }
}

// Configuração do Pipeline HTTP
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "Faturamento Service API v1");
    });
}

app.UseCors("AllowAll");

app.UseAuthorization();

app.MapControllers();

app.Run();
