using System;
using EstoqueService.Data;
using EstoqueService.Services;
using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

// Configuração de Controllers
builder.Services.AddControllers();

// Configuração de CORS para permitir acesso do Frontend Angular
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

// Configuração do PostgreSQL com Entity Framework Core
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? "Host=localhost;Port=5432;Database=korp_db;Username=postgres;Password=1234;Include Error Detail=true";

builder.Services.AddDbContext<EstoqueDbContext>(options =>
{
    options.UseNpgsql(connectionString);
});

// Injeção de Dependência dos Serviços de Domínio
builder.Services.AddScoped<IProdutoService, ProdutoService>();

// Configuração do Swagger / OpenAPI
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Korp - Estoque Service API",
        Version = "v1",
        Description = "Microsserviço de Controle de Estoque e Cadastro de Produtos - Teste Técnico Korp"
    });
});

var app = builder.Build();

// Inicialização Automática da Estrutura do Banco de Dados no PostgreSQL
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    var logger = services.GetRequiredService<ILogger<Program>>();
    try
    {
        var context = services.GetRequiredService<EstoqueDbContext>();
        logger.LogInformation("Garantindo estrutura de tabelas do Estoque no PostgreSQL (Schema: estoque)...");

        context.Database.ExecuteSqlRaw(@"
            DO $$
            BEGIN
                IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'estoque') THEN
                    CREATE SCHEMA estoque;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS estoque.produtos (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                codigo character varying(50) NOT NULL,
                descricao character varying(200) NOT NULL,
                saldo integer NOT NULL DEFAULT 0,
                criado_em timestamp with time zone NOT NULL DEFAULT (NOW()),
                atualizado_em timestamp with time zone
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_produtos_codigo"" ON estoque.produtos (codigo);

            CREATE TABLE IF NOT EXISTS estoque.movimentacoes_estoque (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nota_fiscal_id integer NOT NULL,
                idempotency_key character varying(100),
                produto_id integer NOT NULL,
                quantidade integer NOT NULL,
                motivo character varying(200),
                criado_em timestamp with time zone NOT NULL DEFAULT (NOW())
            );

            CREATE INDEX IF NOT EXISTS ""IX_movimentacoes_estoque_nota_fiscal_id"" ON estoque.movimentacoes_estoque (nota_fiscal_id);
            CREATE INDEX IF NOT EXISTS ""IX_movimentacoes_estoque_idempotency_key"" ON estoque.movimentacoes_estoque (idempotency_key);
        ");

        logger.LogInformation("Estrutura do banco do Estoque inicializada com sucesso.");
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Erro ao inicializar o banco de dados do Estoque.");
    }
}

// Configuração do Pipeline HTTP
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "Estoque Service API v1");
    });
}

app.UseCors("AllowAll");

app.UseAuthorization();

app.MapControllers();

app.Run();
